### ISSUE TITLE
Help needed; not getting results

### ISSUE THREAD

**Issue by KephaSher** [letmaik/lensfunpy#48]
I've run the code in the README on an image, but it doesn't seem to change anything. 

This is what I have right now (I tweaked the parameters to extreme values to see what would happen; nothing did):
<img width="698" alt="Screen Shot 2023-09-30 at 3 42 41 PM" src="https://github.com/letmaik/lensfunpy/assets/87000244/59d5b7de-5829-4561-8f33-81b0dbb7e3f0">

However the results seemed to be exactly the same.

**Comment by letmaik** [comment]
Are you sure the distortion is not just very small so that you don't see a difference immediately? Make sure to include some straight lines in the photo, then it's easier to see. You can also visualize `im_undistorted` to see the remapping coordinates.

**Comment by KephaSher** [comment]
No, the image distortion is very noticeable. I got the test image from this repo: [https://github.com/bbenligiray/lens-distortion-rectification](url).

However, now I'm suspecting that the package was not downloaded correctly since when I import lensfunpy, the error 
`ModuleNotFoundError: No module named 'lensfunpy._lensfun'` pops up, although strangely it only happens sometimes.

Thanks in advance.

**Comment by letmaik** [comment]
I couldn't find what camera/lens was used to capture the test images that you linked to. Without that, I won't be able to reproduce the issue. Are you sure the images were taken with the same lens as in the README? I highly doubt that as the distortion looks much bigger.

Regarding the ModuleNotFoundError, this happens when you run from the folder where the lensfunpy repository is as the imports get mixed up then. Just go into a different folder.

**Comment by abubelinha** [comment]
Could anyone explain me the context for the negative `distance` (250 Km!) in the example code?
Also `focal_length` and `aperture` values sound a bit odd to me. Which units are those?
I couldn't find the image since the link does not point to any particular file.

Thanks
@abubelinha
